### ISSUE TITLE
Examples (plural form) are not allowed, contrary to what the JSON schema spec says

### ISSUE THREAD

**Issue by paps** [APIDevTools/swagger-cli#22]
In the JSON schema spec, it says that to annotate an instance with examples, we can use the `"examples"` property which must be an array https://json-schema.org/latest/json-schema-validation.html#rfc.section.10.4

However, validating a simple OpenAPI 3 document like this one:

```
openapi: 3.0.0
info:
  description: Foobar
  version: "1.0.0"
  title: Foobar
paths:
  '/foobar':
    get:
      responses:
        '200':
          description: this is a description
          content:
            application/json:
              schema:
                type: string
                examples: ["aaaa"]
```

fails with:

```
Swagger schema validation failed. 
  Data does not match any schemas from 'oneOf' at #/paths//foobar/get/responses/200
    Data does not match any schemas from 'oneOf' at #/paths//foobar/get/responses/200/content/application/json/schema                                                                                           
      Additional properties not allowed: examples at #/content/application/json/schema
      Missing required property: $ref at #/content/application/json/schema
    Missing required property: $ref at #/paths//foobar/get/responses/200
 
JSON_OBJECT_VALIDATION_FAILED
```

Keep in mind that I'm not talking about the OpenAPI 3 spec itself, but about the description of inputs and outputs of endpoints using JSON schema.

Replacing `examples: ["aaaa"]` with `example: "aaaa"` makes it work, but then the output description is not a valid JSON schema and other tools that respect the spec fail to interpret it.

I realize that this might not be the best place to report this problem. If that's the case, can somebody redirect me to the correct repo? Thanks!

**Comment by JamesMessinger** [comment]
### Three points (two bad, one good):

**1.** The JSON Schema spec that you linked to is the latest version (Draft-7), but OpenAPI 3.0 only supports the [Wright Draft 00](https://tools.ietf.org/html/draft-wright-json-schema-00), which only has an `example` keyword, not an `examples` keyword.

**2.** OpenAPI is only a [limited subset](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#schema-object) of JSON Schema.  So not even all of the stuff in Wright Draft 00 is supported, and some things that _are_ supported are limited or modified. 

**3.** But here's the good news!  OpenAPI has its own [`examples` property](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#media-type-object) for both requests and responses.  So you can rewrite your API definition like this:

```yaml
openapi: 3.0.0
info:
  description: Foobar
  version: "1.0.0"
  title: Foobar
paths:
  '/foobar':
    get:
      responses:
        '200':
          description: this is a description
          content:
            application/json:
              schema:
                type: string
              examples:
                myFirstExample: aaaa
                mySecondExample: bbb
```

**Comment by paps** [comment]
OK, that's a shame :)

Thanks anyway
