### ISSUE TITLE
Git pre-commit hook integration

### ISSUE THREAD

**Issue by brianroch** [APIDevTools/swagger-cli#26]
It would be very useful to integration the validation functionality with the git pre-commit hook. I am currently working on a Go micro-service project spanning several teams. One such micro-service provides a central API (to the outside world) for all other services. As such, a large API contract is necessary. Given the support of multi-file API definitions, this is the only validation tool I could find that met my requirements.

**Comment by scop** [comment]
With #27 and #36, I think this is taken care of?

**Comment by JamesMessinger** [comment]
Yup.  Good point.  Thanks for catching this old issue
