### ISSUE TITLE
OpenAPI 3.0 Schema link in README.md file is incorrect

### ISSUE THREAD

**Issue by bugb** [APIDevTools/swagger-cli#30]
The link for Open API 3.0 schema (https://github.com/kogosoftwarellc/open-api/blob/master/packages/openapi-schema-validation/schema/openapi-3.0.json) that is located here is dead:

https://github.com/APIDevTools/swagger-cli#validate-an-api

Please fix this.

**Comment by JamesMessinger** [comment]
Fixed! Thanks for catching that
