### ISSUE TITLE
Bundle command broken on version 3.0.0

### ISSUE THREAD

**Issue by superh2m** [APIDevTools/swagger-cli#39]
Hello guys!

At [@Moovone](https://github.com/MoovOne) we use swagger-cli (very useful) in a Docker container context, with the following simplest configuration:
```
FROM node:8.9-alpine

RUN npm install -g swagger-cli

ENTRYPOINT ["swagger-cli"]
```

So every time you post a new version, we retest our swagger spec with it, and this time we found that something not worked correctly!

![Command execution](https://user-images.githubusercontent.com/6178360/73273925-00812000-41e5-11ea-941e-08b2311876fd.jpg)
_This image illustrate how we use swagger-cli_

With the new version 3.0.0 a new error has appeared `Cannot read property 'mkdir' of undefined`

Do you now why? We didn't change anything on our side

**Comment by JamesMessinger** [comment]
Swagger CLI 3.0.0 requires Node 10 or newer.  See [the changelog](https://github.com/APIDevTools/swagger-cli/blob/master/CHANGELOG.md) for details.

Node 8 and older are [no longer maintained](https://nodejs.org/en/about/releases/)
