### ISSUE TITLE
Does swagger-cli work as wrapper?

### ISSUE THREAD

**Issue by ytm100g** [APIDevTools/swagger-cli#40]
I read changelog.

`The "swagger-cli" NPM package is now just a wrapper around the scoped "@apidevtools/swagger-cli" package`

But I cannot install swagger-cli by `npm install swagger-cli`.
I got 404.

Is this right?

**Comment by kedarX** [comment]
It fails with following dependency? cc: @JamesMessinger 
```
  npm ERR! code E404
  npm ERR! 404 Not Found - GET https://registry.npmjs.org/@jsdevtools%2fswagger-cli - Not found
  npm ERR! 404 
  npm ERR! 404  '@jsdevtools/swagger-cli@4.0.1' is not in the npm registry.
```

**Comment by kedarX** [comment]
use`npm install -g @apidevtools/swagger-cli` and `apidevtools/swagger-cli` in package.json

**Comment by ytm100g** [comment]
> use`npm install -g @apidevtools/swagger-cli` and `@apidevtools/swagger-cli` in package.json

It works.Thank you.

**Comment by lorthirk** [comment]
Obviously `npm install -g @apidevtools/swagger-cli` works, but the point is that the wrapper is wrapping around the wrong package. It should be fixed regardless of the use of the scoped package directly, otherwise it's just useless.

**Comment by JamesMessinger** [comment]
Sorry!  This was due to a typo in the wrapper module.  It's been fixed now and released as v4.0.2

**Comment by kedarX** [comment]
Thanks @JamesMessinger

**Comment by ytm100g** [comment]
That’s very kind of you.
