### ISSUE TITLE
"404: '@apidevtools/swagger-cli@latest' is not in the npm registry" when installing package

### ISSUE THREAD

**Issue by idoqo** [APIDevTools/swagger-cli#50]
I don't know what really went wrong but npm seems unable to find the swagger-cli package in the registry. This is the error log I get when I run `npm install -g @apidevtools/swagger-cli`
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@apidevtools%2fswagger-cli - Not found
npm ERR! 404
npm ERR! 404  '@apidevtools/swagger-cli@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/idoko/.npm/_logs/2020-08-06T09_12_34_106Z-debug.log
```
And it happens both on my dev machine and Github Actions.

**Comment by andrejs-sisojevs-accenture** [comment]
could be related to global NPM access issues https://status.npmjs.org/incidents/cksjqc1w11v5

**Comment by JamesMessinger** [comment]
Yeah, this is caused by the NPM problem that @andrejs-sisojevs-accenture pointed out.  It's just temporary. Once NPM resolves the issue, everything should work again.
