### ISSUE TITLE
Dereferencing caches last used `$ref`

### ISSUE THREAD

**Issue by boesing** [APIDevTools/swagger-cli#55]
Hey there,

I am experiencing a strange issue when using dereferencing.

Having two files:

## foo.yaml
```yaml
openapi: "3.0.0"
info: {}
paths:
  /foo/bar:
    get:
      responses:
        200:
          description: OK
```

## bar.yaml
```yaml
openapi: 3.0.0
info: {}
paths:
  /foo/bar:
    get:
      $ref: 'foo.yaml#/paths/~1foo~1bar/get'
      tags:
        - foo
        - bar
      parameters:
        - in: query
          required: true
          name: "foo"
          schema:
            $ref: '#/components/parameters/QueryParameterFoo'

components:
  parameters:
    QueryParameterFoo:
      type: string
```

When using `swagger-cli bundle bar.yaml --dereference`, I get the following error:
```
Error resolving $ref pointer "foo.yaml#/components/parameters/QueryParameterFoo". 
Token "components" does not exist.
```

The error is correct, the file `foo.yaml` does not have the parameter `QueryParameterFoo` within `components/parameters`, but I've never referenced that 🤷‍♂️ 

So what I assume is, that the dereferencing somehow thinks, that it has to look within `foo.yaml` when passing to the next `$ref`.

I am on v2.3.5 - gonna re-check on v4.

## Update
When updating to v4.0.4, the error message is less verbose but ends up with the same problem:
```Token "components" does not exist.```

Am I using the `$ref` wrong or is this supposed to be a bug?

**Comment by boesing** [comment]
@JamesMessinger Is anything missing to triage this issue?
Is this a bug?
Is this intentional?

If there is anything I can do, please let me know.

**Comment by DmytroMysak** [comment]
Same error (((
I have some objects in a separate YAML file and use it in the same schema 2 times as a result of error:
Code:
```
        properties1:
            $ref: "./ExtraProperties.yaml"
        properties2:
            $ref: "./ExtraProperties.yaml"
```
Wrong generated file:
```
          properties1:
                   type: object
                   .....
          properties2:
                  $ref: '#/components/schemas/CreateObject/properties/properties1'
```

**Comment by boesing** [comment]
Closing here as it seems that this repository is unmaintained anymore.
